### ISSUE TITLE
Design templates

### ISSUE THREAD

**Issue by philwinkle** [magento-ecg/coding-standard#15]
This doesn't appear to be executing on design templates? Am I missing something?

**Comment by zlik** [comment]
No templates support yet, sorry.

**Comment by wojtekn** [comment]
@philwinkle do you mean on `.phtml` files? I was able to successfully execute sniffer on template files by providing `--extensions=php,phtml` param to phpcs tool.

However, I extended ECG standard in my custom ruleset file to avoid triggering echo errors in `.phtml` files:

    <rule ref="ecg.Security.LanguageConstruct.DirectOutput">
        <exclude-pattern>*.phtml</exclude-pattern>
    </rule>

**Comment by philwinkle** [comment]
Very nice - exactly what I was looking for!

On Mon, Mar 23, 2015 at 4:20 AM, wojtekn <notifications@github.com> wrote:

> @philwinkle <https://github.com/philwinkle> do you mean on .phtml files?
> I was able to successfully execute sniffer on template files by providing
> --extensions=php,phtml param to phpcs tool.
>
> However, I extended ECG standard in my custom ruleset file to avoid
> triggering echo errors in .phtml files:
>
> <rule ref="ecg.Security.LanguageConstruct.DirectOutput">
>     <exclude-pattern>*.phtml</exclude-pattern>
> </rule>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento-ecg/coding-standard/issues/15#issuecomment-84880812>
> .
>



-- 

Follow me on Twitter - @philwinkle
Friend me on Facebook - http://www.facebook.com/philwinkle
