### ISSUE TITLE
something bad in this functions?

### ISSUE THREAD

**Issue by luckyraul** [magento-ecg/coding-standard#17]
12 | ERROR | The use of function tempnam() is forbidden
 20 | ERROR | The use of function pathinfo() is forbidden
 35 | ERROR | The use of function unlink() is forbidden

**Comment by zlik** [comment]
Nothing particularly bad, they just work as indicators of a potential problem. Also, can be too low level - in Magento Zend or Varien adapters are usually instead of low level PHP functions. This should be probably marked as WARNING, not ERROR.

**Comment by riker09** [comment]
Does anyone know an alternative to `pathinfo()`? I know it's kind of low level, but this function is so very useful. I really don't think it should be in the list of forbidden functions.

A WARNING should be sufficient and I would gladly provide a PR, but I have no clue where to start.
