### ISSUE TITLE
No code style checks

### ISSUE THREAD

**Issue by Zifius** [magento-ecg/coding-standard#21]
I didn't follow the updates closely but for some reason the standard stopped doing code style checks for me. My guess is the version 2.x (2.3.0 as of now) of the phpcs

Ecg.Security.ForbiddenFunction and Ecg.Performance sniffs still run ok. Any clues are appreciated

**Comment by tim-bezhashvyly** [comment]
Error message?

**Comment by Zifius** [comment]
@tim-bezhashvyly no errors, just no style checks. Some info about this in #18, but I'm more curious at which point the style checks were removed, can't find the related commit

**Comment by zlik** [comment]
@Zifius, we are not doing any style checks like formatting or naming, because there're Magento 2 and ZF rules for that. Our standard is rather about more severe coding issues related to performance, security, maintainability, etc.

Please let us know if you have any problems running existing sniffs.

**Comment by Zifius** [comment]
Thanks Andriy, no problems what so far was just curious when exactly the code style checks were removed. I understand your reasoning, but we can't enable e.g. two coding standards in PhpStorm IDE, right?

**Comment by tim-bezhashvyly** [comment]
If you would like to use ECG coding standard and let's say ZF standard I suggest creating your own standard containing of just one ruleset XML which will inherit from required standards:

```xml
<?xml version="1.0"?>
<ruleset name="Zifius">
    <rule ref="Zend"/>
    <rule ref="/absolute/path/to/magento-ecg/coding-standar/ruleset.xml"/>
</ruleset>
```

**Comment by Zifius** [comment]
Cool, thanks Tim!
