### ISSUE TITLE
Referenced sniff "Ecg.Security.LanguageConstruct.DirectOutput" does not exist

### ISSUE THREAD

**Issue by morfcz** [magento-ecg/coding-standard#22]
Hi,

i wanted to use your project, to check my Magento module. However it doesn't work (i have tried both coding standards 1.2 version + php code sniffer 2.3.3 ... and latest versions from master - both have the same issue.

$ ../PHP_CodeSniffer-2.3.3/scripts/phpcs --standard=../coding-standard-1.2 ModuleName/ > standards2.txt

```
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "Ecg.Security.LanguageConstruct.DirectOutput" does not exist' in /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer.php:1092

Stack trace:
#0 /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer.php(733): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/workspace/...', 0)
#1 /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer.php(551): PHP_CodeSniffer->processRuleset('/workspace/...')
#2 /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer/CLI.php(818): PHP_CodeSniffer->initStandard(Array, Array)
#3 /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /workspace/PHP_CodeSniffer-2.3.3/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /workspace/PHP_CodeSniffer-2.3.3/CodeSniffer.php on line 1092
```

**Comment by morfcz** [comment]
Nevermind, my bad...

**Comment by googlygoo** [comment]
Hi, 
could you please comment on what you did to fix this as I am having the same issue. Thank you.

**Comment by morfcz** [comment]
Put this repository here:

CodeSniffer/Standards/Ecg/ (check if the paths are correct, for example: 
CodeSniffer/Standards/Ecg/composer.json)

And use it like this:

PHP_CodeSniffer-2.3.3/scripts/phpcs --standard=ecg DirectoryToCheck/

**Comment by googlygoo** [comment]
Thank You. I thought i was being clever and changed the name of the folder from Ecg to Magento which caused all my issues.

**Comment by wsakaren** [comment]
If you get this problem in PHPStorm set up structure as above to fix.  I'm not sure why the repo is not just in that structure to start, would make a lot more sense.
