### ISSUE TITLE
Extending Zend standard

### ISSUE THREAD

**Issue by adragus-inviqa** [magento-ecg/coding-standard#23]
Hello.

I was thinking that this standard shouldn't be standalone, but extending the `Zend` one - with `<rule ref="Zend"/>`.

What do you think?

**Comment by Zifius** [comment]
That's exactly what I did here: https://github.com/Zifius/Magizendo after discussion in #21

**Comment by adragus-inviqa** [comment]
Yeah, I was hoping I could avoid that by using just one/this standard. Guess not.

**Comment by zlik** [comment]
@adragus-inviqa, we want to keep the standard standalone for flexibility. You can create your own `ruleset.xml` and combine rules from different standards in it as you want, like user @Zifius did.

**Comment by adragus-inviqa** [comment]
@zlik - Ok, no problem. I understand. 

My only problem is that, if you check your code with this standard, Zend rules will not be checked. And that would be incorrect. A Magento standard _includes_ a Zend standard (or whatever standard). This repo is not exactly a standard, it's just a grouping of rules.
