### ISSUE TITLE
Warning message for non-plugin class

### ISSUE THREAD

**Issue by mcspronko** [magento-ecg/coding-standard#35]
In case child class extends Magento\Framework\App\Config\Value class with afterSave() method a Warning message is shown:
_Plugin afterSave function should have at least two parameters._

Note: there is no plugin declaration in di.xml file.

**Comment by zlik** [comment]
@mcspronko, we'll have someone look into this. Thank you for reporting.

**Comment by zhooravlik** [comment]
Fixed by commit [`561266f`](https://github.com/magento-ecg/coding-standard/commit/561266f0ea9bfc4731ea5fa107e941d13e47a242).
[PR#63](https://github.com/magento-ecg/coding-standard/pull/63) created, will be merged to master soon.
Closing the issue.
