### ISSUE TITLE
Can't use EcgM2 with composer

### ISSUE THREAD

**Issue by giacmir** [magento-ecg/coding-standard#37]
I'm using EcgM2 and I tought that it would be nice to add it as a dependency with composer and setup with a custom phpcs.xml so that every one in the team can use it more easily.

But if I add this line in phpcs.xml
`<rule ref="./vendor/magento-ecg/coding-standard/EcgM2"/>`

phpcs dies with this error:
`PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Ecg.Performance.CollectionCount" does not exist`

While if I try to add Ecg it works (but since it is a Magento 2 project I don't need it)

**Comment by zlik** [comment]
Hi Giacomo,

Thank you for reporting this issue. We'll look into it. 

Regards,
Alex

**Comment by philwinkle** [comment]
@AlexanderVekerik still broken 2 months later. Any update??

**Comment by philwinkle** [comment]
@zlik this should be fixed with #40

**Comment by siment** [comment]
@zlik Could you please create a release with @philwinkle's change so we can pull package from [Packagist](https://packagist.org/packages/magento-ecg/coding-standard)?

**Comment by SantoDE** [comment]
That would be awesome @philwinkle

**Comment by Zifius** [comment]
@giacmir Are we good to close this issue or there are still problems? EcgM2 depends on Ecg standard so it's not possible to install just M2 version at the moment

@siment FYI releases 2.1 and 3.0 are created

**Comment by giacmir** [comment]
@Zifius I consider this issue solved for me.

**Comment by Zifius** [comment]
@giacmir thanks for feedback
