### ISSUE TITLE
Can you please do more frequest releases?

### ISSUE THREAD

**Issue by adragus-inviqa** [magento-ecg/coding-standard#41]
Is the release schedule of this repo tied to the M2 one? I'd rather this one be separate and have small, but more frequent tags/release, so we can use it via composer in a more elegant way, not using `master`.

**Comment by jamescowie** [comment]
Just reviving this issue. I think its a very good point @adragus-inviqa and code standards should not be tied to the version of M2 as they are separate entity and constantly evolving. I have a pull request up coming that hopefully will help with this and then clear tagging policy can be made clear.

**Comment by zlik** [comment]
@adragus-inviqa, the release schedule, and tagging are not tied to M2. New releases/tags are created with every significant contribution.

**Comment by Zifius** [comment]
@zlik I think we should do minor releases as well, e.g. to target fixes as well
