### ISSUE TITLE
Coding Standard Clarification

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento-ecg/coding-standard#42]
Hi,
I have installed PHP_Codesniffer extension to find out the magento 2 coding standard issues.
I have run the below command.
	"phpcs --standard=Ecg --extensions=php,xml,phtml --report-full=/path/testing.log /path/"

This extension lists out many errors in the log file from default magento 2 itself.

So, kindly let me know how to say that the default magento 2 coding standard has so many issues.

**Comment by Zifius** [comment]
Hi @ewallkrishnaprakash, Magento 2 is under heavy development and v2.2 which will be released in the coming months should include fixes to the coding standards as well. You are more then welcome to submit a PR against Magento 2 repository to fix some of these as well

Hope this answers your question
