### ISSUE TITLE
Shall we folllow the official coding standards?

### ISSUE THREAD

**Issue by nntoan** [magento-ecg/coding-standard#47]
Hello,

Magento 2 just published [Technical Guidelines](http://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines/technical-guidelines.html) and it's pretty cool.

As per as:

> 2.7. All non-public properties and methods SHOULD be private.

This currently displays a warning with EcgM2, like M1 we warning about `private` methods and properties.

There are something more, should we improve it to prepare for a better 2.2 release?

P/s: To whom may concern, if you want to make this work. Please follow this pull request: #45

**Comment by zlik** [comment]
This has been addressed in [#45](https://github.com/magento-ecg/coding-standard/pull/45). Thank you, @nntoan!
