### ISSUE TITLE
Access level on Ecg_Sniffs_Security_ForbiddenFunctionSniff

### ISSUE THREAD

**Issue by centerax** [magento-ecg/coding-standard#9]
Getting this error while trying to run phpcs with this standard.
`Registering sniffs in the Ecg standard... PHP Fatal error:  Access level to Ecg_Sniffs_Security_ForbiddenFunctionSniff::$forbiddenFunctions must be public (as in class Generic_Sniffs_PHP_ForbiddenFunctionsSniff) in vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php on line 4`

I changed that class property to public and it runs fine.

**Comment by yireo** [comment]
Fix works perfectly for me too.
